version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://resumeuser:resumepassword@postgres:5432/resumebuilder
      - PGUSER=resumeuser
      - PGPASSWORD=resumepassword
      - PGDATABASE=resumebuilder
      - PGHOST=postgres
      - PGPORT=5432
      - SESSION_SECRET=resume_builder_session_secret
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=resumeuser
      - POSTGRES_PASSWORD=resumepassword
      - POSTGRES_DB=resumebuilder
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Optional adminer service for database management via web UI
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: